feat: cleaner python json snippets
Kong/httpsnippet pull request #189
Opened 2020-10-16 00:41 UTC by erunion

This cleans up the snippets that are coming from the Python `requests` client to:

* [x] Ensure that all dict keys are wrapped in double quotes (most everything already was).
* [x] For `application/json` requests, we now build out Python-compatible dicts and send pass those to `requests` via the `json=payload` argument that it provides.
  * With this work, `false`, `true`, and `null` are now being translated into the Python-proper literals of `False`, `True`, and `None`.

2020-10-21 17:50 UTC, DMarby requested changes
Thank you for this contribution!
Just one minor note about the function documentation on buildString

2020-10-21 17:50 UTC, DMarby commented on src/targets/python/helpers.js
> + * Create an string of given length filled with blank spaces
I think this function documentation needs to be updated, as it's missing the second argument which is what is used to build the resulting string out of

2020-10-21 21:17 UTC, erunion commented
@DMarby Updated that docblock, and since I copied that function from `src/targets/swift/helpers.js` I've also updated it there since it was missing as well.

Once this library gets some Babel compilation, these string padding methods could probably removed in favor of `String.prototype.padStart` and `String.prototype.padEnd`.

2020-10-22 11:38 UTC, DMarby approved these changes
LGTM :shipit:

2020-11-27 03:48 UTC, develohpanda approved these changes
Thanks for doing this! I think a conflict was introduced by your other PR I just merged - #188 😅

2020-11-27 17:37 UTC, erunion commented
@develohpanda Fixed the merge conflict so this should be good to go.

2020-11-29 11:44 UTC, develohpanda commented
Hi @erunion, it looks like [one of the tests](https://travis-ci.org/github/Kong/httpsnippet/jobs/746357535#L1719) from the merge conflict is now failing 🙁 just need to fix up the expected double-quotes in that I think!

2020-12-01 19:32 UTC, erunion commented
@develohpanda Oops, sorry about that. Fixed now.

2020-12-01 22:09 UTC, merged