Add parameter to enable decode url for place holder
Kong/httpsnippet pull request #205
Opened 2021-02-08 08:31 UTC by lzyLuke

Hi, forks.
I am experiencing some issues of using this library.
Say I have a url : http://mockbin.com/request/{id}, the {id} is a place holder. When generating snippets, I do not want the place holder to be uri encoded. 
If I use current code: there would be a  "http://mockbin.com/request/%7Bid%7D"
But I actually want "http://mockbin.com/request/{id}" here.

So add a switch on httpSnippet to decide whether we should use uriencode here. (Default is yes, so there will not be a breaking change)

2021-02-08 08:31 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Kong/httpsnippet?pullRequest=205) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Kong/httpsnippet?pullRequest=205) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Kong/httpsnippet?pullRequest=205) it.</sub>

2021-04-05 16:39 UTC, reynolek commented
Hey @lzyLuke! This looks like a useful change. Sorry it took me so long to get to it!

2021-04-05 16:40 UTC, reynolek requested changes
The change itself looks fine to me, but would you mind adding some test coverage so that Future Us doesn't unintentionally break this functionality?

2022-07-18 20:10 UTC, dimitropoulos commented
see https://github.com/Kong/httpsnippet/pull/290/

2022-07-18 20:10 UTC, closed without merging