Add target for Reqwest library for Rust
Kong/httpsnippet pull request #242
Opened 2022-02-02 21:28 UTC by uWynell

2022-02-03 07:47 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Kong/httpsnippet?pullRequest=242) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Kong/httpsnippet?pullRequest=242) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Kong/httpsnippet?pullRequest=242) it.</sub>

2022-02-03 17:06 UTC, erunion requested changes
Can you add the necessary test fixtures for this new target?

2022-02-03 17:06 UTC, erunion commented on package.json
> +  "version": "2.1.0",
Shouldn't need to do this in a PR, when they publish a release they'll handle this.

2022-02-23 10:11 UTC, closed without merging

2022-04-13 20:50 UTC, dimitropoulos commented
@uWynell not sure why this closed, but just wanted to point your attention to https://github.com/Kong/httpsnippet/pull/248 which may be merging soon.  one of the things I hope to do after launch is get a rust target in.  if you have any interest in continuing this work please let me know!

2022-04-24 16:47 UTC, uWynell commented
@dimitropoulos Yep, I'd like to implmenet a target for reqwest similarly to other targets in #248. If it's not urgent, I will do it in about a week. Or I can hurry up, if necessary.
P.S. I don't remember myself why I closed this pull :\

2022-04-26 12:37 UTC, dimitropoulos commented
cool, lemme know how it goes!  Just merged #248 so you should be good to start on it whenever you feel like or have time :)

2023-07-29 19:34 UTC, SKPG-Tech commented
Any plans on continuing this?