add header namesspace to prevent header errors
Kong/httpsnippet pull request #247
Opened 2022-02-17 22:26 UTC by davismartin

## Description 

Currently, if I try to just run the snippets produced by this charp -> httpclient.js target then I will get errors similar to 
```
error CS0246: The type or namespace name 'ContentDispositionHeaderValue' could not be found
```

However, if I add the namespace `using System.Net.Http.Headers;` to the top then the snippet works as expected

This PR just adds that namespace to the top so that the snippet can run if just copied.

2022-02-17 22:28 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Kong/httpsnippet?pullRequest=247) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Kong/httpsnippet?pullRequest=247) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Kong/httpsnippet?pullRequest=247) it.</sub>

2022-02-17 23:30 UTC, erunion requested changes
Can you update the test fixtures with this new line?

2022-02-18 19:05 UTC, erunion approved these changes

2022-07-13 19:57 UTC, dimitropoulos approved these changes
(I rebased it into TypeScript-land) looks good to me!  I wondered if it'd be more nature to have a new line after the `using` statement.  but all good.  we can easily add later to tweak if so.  figured I'd default to someone that's clearly familar with csharp these days (@davismartin)

2022-07-13 19:58 UTC, merged